### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by moussa-b** [certifaction/cli#17]
Hi,

I think that there is a typo in the documentation : https://github.com/certifaction/cli#query-parameters-7
Shouldn't be `new-email` instead of `new-emain` ?

![typo_error](https://user-images.githubusercontent.com/26151311/182386344-a9ff282b-adfe-4f87-b888-c0b6779b09cd.png)

Thanx

**Comment by ianaz** [comment]
Thanks @moussa-b for reporting, you're right :) 
We'll provide a fix soon

**Comment by moussa-b** [comment]
You're welcome @ianaz

**Comment by ianaz** [comment]
Fixed in https://github.com/certifaction/cli/pull/18
